export enum Subject {
  ANTHROPOLOGY = 'Anthropologie',
  ARCHAEOLOGY = 'Archäologie',
  ASTRONOMY = 'Astronomie',
  BIOLOGY = 'Biologie',
  CHEMISTRY = 'Chemie',
  ETHICS = 'Ethik',
  FOREIGN_LANGUAGES = 'Fremdsprachen',
  GEOGRAPHY = 'Geographie',
  HISTORY = 'Geschichte',
  COMPUTER_SCIENCE = 'Informatik',
  ART = 'Kunst',
  LITERATURE = 'Literatur',
  MATHEMATICS = 'Mathematik',
  MUSIC = 'Musik',
  PHYSICS = 'Physik',
  POLITICAL_SCIENCE = 'Politikwissenschaft',
  PSYCHOLOGY = 'Psychologie',
  EDUCATION = 'Pädagogik',
  PHILOSOPHY = 'Philosophie',
  LAW = 'Rechtswissenschaft',
  RELIGION = 'Religion',
  SOCIOLOGY = 'Soziologie',
  PHYSICAL_EDUCATION = 'Sport',
  ENVIRONMENTAL_SCIENCE = 'Umweltwissenschaften',
  ECONOMICS = 'Wirtschaft'

}
